/* File: ExampleInterface.i, generated by mk_interface.py */
%module ExampleInterface 

%{
#include <ExampleInterface.hpp>
#include <iostream>
#include <vector>
%}

%include "src/ExampleInterface.hpp"

%template(ExampleInterfaceExpArray) ExampleInterfaceArray< ExampleInterface_Expression* >;
%template(ExampleInterfaceIntArray) ExampleInterfaceArray< int >;
%template(ExampleInterfaceDoubleArray) ExampleInterfaceArray< double >;

